version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=mywebdb;Username=mywebuser;Password=mywebpassword
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=mywebdb
      - POSTGRES_USER=mywebuser
      - POSTGRES_PASSWORD=mywebpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
